export const ENDPOINTS = {
  account: "accounts",
  bartable: "bartables",
  brand: "brands",
  category: "categories",
  employee: "employees",
  notification: "notifications",
  payment: "payments",
  product: "products",
  productSold: "productsSold",
  provider: "providers",
  sale: "sales",
  transaction: "transactions",
  user: "users",
};
